name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test
    container:
      image: node:14.16.1-alpine3.10
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - run : echo $GITHUB_WORKSPACE
    - run : pwd
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_TEST: ${{ secrets.TEST }}
        envkey_HELLO: ${{ secrets.HELLO }}
        directory: ${{ github.workspace }}
    - run : ls
    - run : cat .env
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: .env
        path: .env
        retention-days: 1
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - name: install node modules
      run : npm ci
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
    container:
      image: node:14.16.1-alpine3.10
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - run : pwd
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: .env
    - run: ls
    - run: cat ./.env
    - name: copy env file 
      run: mv ./.env.example ./.env
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: install node modules
      run : npm ci
    - run: npm start
    - run: echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
    - run: echo Test $TEST
    - run: echo Hello $HELLO
    - run: cat .env