name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
 
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_TEST: ${{ secrets.TEST }}
        envkey_HELLO: ${{ secrets.HELLO }}
        directory: ./
        file_name: .env
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
    container:
      image: node:14.16.1-alpine3.10
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - uses: actions/checkout@v2
    - run: mv ./.env.example ./.env
    - run: npm ci
    - run: npm start
    - run: echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
    - run: echo Test $TEST
    - run: echo Hello $HELLO
    - run: cat ./.env