name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - run : echo $GITHUB_WORKSPACE
    - run : pwd
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_TEST: ${{ secrets.TEST }}
        envkey_HELLO: ${{ secrets.HELLO }}
        directory: ${{ github.workspace }}
    - run : cat .env
    - name: NPM ci and cacheing
      uses: bahmutov/npm-install@v1
      with:
        useRollingCache: true
        NODE_ENV: dev
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: test
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run : pwd
    - run: ls
    - name: copy env file 
      run: mv ./.env.example ./.env
    - uses: bahmutov/npm-install@v1
      with:
        useRollingCache: true
        NODE_ENV: production
    - run: npm start
    - run: echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
    - run: echo Test $TEST
    - run: echo Hello $HELLO
    - run: cat .env
    - run: echo github.ref $github.ref