name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    container:
      image: node:14.16.1-alpine3.10
    env:
      TEST: ${{ secrets.TEST }}
      HELLO: ${{ secrets.HELLO }}
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm start
    - run: echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
    - run: echo Test $TEST
    - run: echo Hello $HELLO